<?php

declare(strict_types=1);

namespace App\DBClientFile\Support;

use MyCLabs\Enum\Enum;

/**
 * Class DBClientFile.
 *
 * @psalm-immutable
 *
 * @method static int|DBClientFile Achievement()
 * @method static int|DBClientFile Achievement_Category()
 * @method static int|DBClientFile AdventureJournal()
 * @method static int|DBClientFile AdventureMapPOI()
 * @method static int|DBClientFile AlliedRace()
 * @method static int|DBClientFile AnimKit()
 * @method static int|DBClientFile AnimKitBoneSet()
 * @method static int|DBClientFile AnimKitBoneSetAlias()
 * @method static int|DBClientFile AnimKitConfig()
 * @method static int|DBClientFile AnimKitConfigBoneSet()
 * @method static int|DBClientFile AnimKitPriority()
 * @method static int|DBClientFile AnimKitReplacement()
 * @method static int|DBClientFile AnimKitSegment()
 * @method static int|DBClientFile AnimReplacement()
 * @method static int|DBClientFile AnimReplacementSet()
 * @method static int|DBClientFile AnimaCable()
 * @method static int|DBClientFile AnimaCylinder()
 * @method static int|DBClientFile AnimaMaterial()
 * @method static int|DBClientFile AnimationData()
 * @method static int|DBClientFile AreaConditionalData()
 * @method static int|DBClientFile AreaFarClipOverride()
 * @method static int|DBClientFile AreaGroupMember()
 * @method static int|DBClientFile AreaPOI()
 * @method static int|DBClientFile AreaPOIState()
 * @method static int|DBClientFile AreaTable()
 * @method static int|DBClientFile AreaTrigger()
 * @method static int|DBClientFile AreaTriggerActionSet()
 * @method static int|DBClientFile AreaTriggerBox()
 * @method static int|DBClientFile AreaTriggerCreateProperties()
 * @method static int|DBClientFile AreaTriggerCylinder()
 * @method static int|DBClientFile AreaTriggerSphere()
 * @method static int|DBClientFile ArenaCcItem()
 * @method static int|DBClientFile ArmorLocation()
 * @method static int|DBClientFile Artifact()
 * @method static int|DBClientFile ArtifactAppearance()
 * @method static int|DBClientFile ArtifactAppearanceSet()
 * @method static int|DBClientFile ArtifactCategory()
 * @method static int|DBClientFile ArtifactItemToTransmog()
 * @method static int|DBClientFile ArtifactPower()
 * @method static int|DBClientFile ArtifactPowerLink()
 * @method static int|DBClientFile ArtifactPowerPicker()
 * @method static int|DBClientFile ArtifactPowerRank()
 * @method static int|DBClientFile ArtifactQuestXP()
 * @method static int|DBClientFile ArtifactTier()
 * @method static int|DBClientFile ArtifactUnlock()
 * @method static int|DBClientFile AuctionHouse()
 * @method static int|DBClientFile AzeriteEmpoweredItem()
 * @method static int|DBClientFile AzeriteEssence()
 * @method static int|DBClientFile AzeriteEssencePower()
 * @method static int|DBClientFile AzeriteItem()
 * @method static int|DBClientFile AzeriteItemMilestonePower()
 * @method static int|DBClientFile AzeriteKnowledgeMultiplier()
 * @method static int|DBClientFile AzeriteLevelInfo()
 * @method static int|DBClientFile AzeritePower()
 * @method static int|DBClientFile AzeritePowerSetMember()
 * @method static int|DBClientFile AzeriteTierUnlock()
 * @method static int|DBClientFile AzeriteTierUnlockSet()
 * @method static int|DBClientFile AzeriteUnlockMapping()
 * @method static int|DBClientFile BankBagSlotPrices()
 * @method static int|DBClientFile BannedAddons()
 * @method static int|DBClientFile BarberShopStyle()
 * @method static int|DBClientFile BarrageEffect()
 * @method static int|DBClientFile BattlePetAbility()
 * @method static int|DBClientFile BattlePetAbilityEffect()
 * @method static int|DBClientFile BattlePetAbilityState()
 * @method static int|DBClientFile BattlePetAbilityTurn()
 * @method static int|DBClientFile BattlePetBreedQuality()
 * @method static int|DBClientFile BattlePetBreedState()
 * @method static int|DBClientFile BattlePetDisplayOverride()
 * @method static int|DBClientFile BattlePetEffectProperties()
 * @method static int|DBClientFile BattlePetNPCTeamMember()
 * @method static int|DBClientFile BattlePetSpecies()
 * @method static int|DBClientFile BattlePetSpeciesState()
 * @method static int|DBClientFile BattlePetSpeciesXAbility()
 * @method static int|DBClientFile BattlePetSpeciesXCovenant()
 * @method static int|DBClientFile BattlePetState()
 * @method static int|DBClientFile BattlePetVisual()
 * @method static int|DBClientFile BattlemasterList()
 * @method static int|DBClientFile BeamEffect()
 * @method static int|DBClientFile BoneWindModifierModel()
 * @method static int|DBClientFile BoneWindModifiers()
 * @method static int|DBClientFile BonusRoll()
 * @method static int|DBClientFile Bounty()
 * @method static int|DBClientFile BountySet()
 * @method static int|DBClientFile BroadcastText()
 * @method static int|DBClientFile BroadcastTextDuration()
 * @method static int|DBClientFile CameraEffect()
 * @method static int|DBClientFile CameraEffectEntry()
 * @method static int|DBClientFile CameraMode()
 * @method static int|DBClientFile Campaign()
 * @method static int|DBClientFile CampaignXCondition()
 * @method static int|DBClientFile CampaignXQuestLine()
 * @method static int|DBClientFile CastableRaidBuffs()
 * @method static int|DBClientFile CelestialBody()
 * @method static int|DBClientFile Cfg_Categories()
 * @method static int|DBClientFile Cfg_Configs()
 * @method static int|DBClientFile Cfg_Regions()
 * @method static int|DBClientFile ChallengeModeItemBonusOverride()
 * @method static int|DBClientFile CharBaseInfo()
 * @method static int|DBClientFile CharBaseSection()
 * @method static int|DBClientFile CharComponentTextureLayouts()
 * @method static int|DBClientFile CharComponentTextureSections()
 * @method static int|DBClientFile CharHairGeosets()
 * @method static int|DBClientFile CharSectionCondition()
 * @method static int|DBClientFile CharShipment()
 * @method static int|DBClientFile CharShipmentContainer()
 * @method static int|DBClientFile CharStartKit()
 * @method static int|DBClientFile CharTitles()
 * @method static int|DBClientFile CharacterFacialHairStyles()
 * @method static int|DBClientFile CharacterLoadout()
 * @method static int|DBClientFile CharacterLoadoutItem()
 * @method static int|DBClientFile CharacterLoadoutPet()
 * @method static int|DBClientFile CharacterServiceInfo()
 * @method static int|DBClientFile ChatChannels()
 * @method static int|DBClientFile ChatProfanity()
 * @method static int|DBClientFile ChrClassRaceSex()
 * @method static int|DBClientFile ChrClassTitle()
 * @method static int|DBClientFile ChrClassUIChrModelInfo()
 * @method static int|DBClientFile ChrClassUIDisplay()
 * @method static int|DBClientFile ChrClassVillain()
 * @method static int|DBClientFile ChrClasses()
 * @method static int|DBClientFile ChrClassesXPowerTypes()
 * @method static int|DBClientFile ChrCreateClassAnimTarget()
 * @method static int|DBClientFile ChrCreateClassAnimTargetInfo()
 * @method static int|DBClientFile ChrCustClientChoiceConversion()
 * @method static int|DBClientFile ChrCustItemGeoModify()
 * @method static int|DBClientFile ChrCustomization()
 * @method static int|DBClientFile ChrCustomizationBoneSet()
 * @method static int|DBClientFile ChrCustomizationCategory()
 * @method static int|DBClientFile ChrCustomizationChoice()
 * @method static int|DBClientFile ChrCustomizationCondModel()
 * @method static int|DBClientFile ChrCustomizationConversion()
 * @method static int|DBClientFile ChrCustomizationDisplayInfo()
 * @method static int|DBClientFile ChrCustomizationElement()
 * @method static int|DBClientFile ChrCustomizationGeoset()
 * @method static int|DBClientFile ChrCustomizationMaterial()
 * @method static int|DBClientFile ChrCustomizationOption()
 * @method static int|DBClientFile ChrCustomizationReq()
 * @method static int|DBClientFile ChrCustomizationReqChoice()
 * @method static int|DBClientFile ChrCustomizationSkinnedModel()
 * @method static int|DBClientFile ChrModel()
 * @method static int|DBClientFile ChrModelMaterial()
 * @method static int|DBClientFile ChrModelTextureLayer()
 * @method static int|DBClientFile ChrRaceRacialAbility()
 * @method static int|DBClientFile ChrRaceXChrModel()
 * @method static int|DBClientFile ChrRaces()
 * @method static int|DBClientFile ChrSpecialization()
 * @method static int|DBClientFile ChrUpgradeBucket()
 * @method static int|DBClientFile ChrUpgradeBucketSpell()
 * @method static int|DBClientFile ChrUpgradeTier()
 * @method static int|DBClientFile CinematicCamera()
 * @method static int|DBClientFile CinematicSequences()
 * @method static int|DBClientFile ClientSceneEffect()
 * @method static int|DBClientFile CloakDampening()
 * @method static int|DBClientFile CloneEffect()
 * @method static int|DBClientFile CombatCondition()
 * @method static int|DBClientFile CommentatorIndirectSpell()
 * @method static int|DBClientFile CommentatorStartLocation()
 * @method static int|DBClientFile CommentatorTrackedCooldown()
 * @method static int|DBClientFile CommunityIcon()
 * @method static int|DBClientFile ComponentModelFileData()
 * @method static int|DBClientFile ComponentTextureFileData()
 * @method static int|DBClientFile ConditionalContentTuning()
 * @method static int|DBClientFile ConfigurationWarning()
 * @method static int|DBClientFile ContentRestrictionRuleSet()
 * @method static int|DBClientFile ContentTuning()
 * @method static int|DBClientFile ContentTuningXExpected()
 * @method static int|DBClientFile Contribution()
 * @method static int|DBClientFile ContributionStyle()
 * @method static int|DBClientFile ContributionStyleContainer()
 * @method static int|DBClientFile ConversationLine()
 * @method static int|DBClientFile CorruptionEffects()
 * @method static int|DBClientFile Covenant()
 * @method static int|DBClientFile Creature()
 * @method static int|DBClientFile CreatureDifficulty()
 * @method static int|DBClientFile CreatureDispXUiCamera()
 * @method static int|DBClientFile CreatureDisplayInfo()
 * @method static int|DBClientFile CreatureDisplayInfoCond()
 * @method static int|DBClientFile CreatureDisplayInfoCondXChoice()
 * @method static int|DBClientFile CreatureDisplayInfoEvt()
 * @method static int|DBClientFile CreatureDisplayInfoExtra()
 * @method static int|DBClientFile CreatureDisplayInfoGeosetData()
 * @method static int|DBClientFile CreatureDisplayInfoOption()
 * @method static int|DBClientFile CreatureDisplayInfoTrn()
 * @method static int|DBClientFile CreatureFamily()
 * @method static int|DBClientFile CreatureImmunities()
 * @method static int|DBClientFile CreatureModelData()
 * @method static int|DBClientFile CreatureMovementInfo()
 * @method static int|DBClientFile CreatureSoundData()
 * @method static int|DBClientFile CreatureSoundFidget()
 * @method static int|DBClientFile CreatureType()
 * @method static int|DBClientFile CreatureXContribution()
 * @method static int|DBClientFile CreatureXDisplayInfo()
 * @method static int|DBClientFile CreatureXUiWidgetSet()
 * @method static int|DBClientFile Criteria()
 * @method static int|DBClientFile CriteriaTree()
 * @method static int|DBClientFile CriteriaTreeXEffect()
 * @method static int|DBClientFile CurrencyCategory()
 * @method static int|DBClientFile CurrencyContainer()
 * @method static int|DBClientFile CurrencyTypes()
 * @method static int|DBClientFile Curve()
 * @method static int|DBClientFile CurvePoint()
 * @method static int|DBClientFile DeathThudLookups()
 * @method static int|DBClientFile DecalProperties()
 * @method static int|DBClientFile DeclinedWord()
 * @method static int|DBClientFile DeclinedWordCases()
 * @method static int|DBClientFile DestructibleModelData()
 * @method static int|DBClientFile DeviceBlacklist()
 * @method static int|DBClientFile Difficulty()
 * @method static int|DBClientFile DisplaySeason()
 * @method static int|DBClientFile DissolveEffect()
 * @method static int|DBClientFile DriverBlacklist()
 * @method static int|DBClientFile DungeonEncounter()
 * @method static int|DBClientFile DurabilityCosts()
 * @method static int|DBClientFile DurabilityQuality()
 * @method static int|DBClientFile EdgeGlowEffect()
 * @method static int|DBClientFile Emotes()
 * @method static int|DBClientFile EmotesText()
 * @method static int|DBClientFile EmotesTextData()
 * @method static int|DBClientFile EmotesTextSound()
 * @method static int|DBClientFile EnvironmentalDamage()
 * @method static int|DBClientFile Exhaustion()
 * @method static int|DBClientFile ExpectedStat()
 * @method static int|DBClientFile ExpectedStatMod()
 * @method static int|DBClientFile ExtraAbilityInfo()
 * @method static int|DBClientFile Faction()
 * @method static int|DBClientFile FactionGroup()
 * @method static int|DBClientFile FactionTemplate()
 * @method static int|DBClientFile FootprintTextures()
 * @method static int|DBClientFile FootstepTerrainLookup()
 * @method static int|DBClientFile FriendshipRepReaction()
 * @method static int|DBClientFile FriendshipReputation()
 * @method static int|DBClientFile FullScreenEffect()
 * @method static int|DBClientFile GMSurveyAnswers()
 * @method static int|DBClientFile GMSurveyCurrentSurvey()
 * @method static int|DBClientFile GMSurveyQuestions()
 * @method static int|DBClientFile GMSurveySurveys()
 * @method static int|DBClientFile GameClockDebug()
 * @method static int|DBClientFile GameObjectAnimGroupMember()
 * @method static int|DBClientFile GameObjectArtKit()
 * @method static int|DBClientFile GameObjectDiffAnimMap()
 * @method static int|DBClientFile GameObjectDisplayInfo()
 * @method static int|DBClientFile GameObjectDisplayInfoXSoundKit()
 * @method static int|DBClientFile GameObjects()
 * @method static int|DBClientFile GameParameter()
 * @method static int|DBClientFile GameTips()
 * @method static int|DBClientFile GarrAbility()
 * @method static int|DBClientFile GarrAbilityCategory()
 * @method static int|DBClientFile GarrAbilityEffect()
 * @method static int|DBClientFile GarrAutoCombatant()
 * @method static int|DBClientFile GarrAutoSpell()
 * @method static int|DBClientFile GarrAutoSpellEffect()
 * @method static int|DBClientFile GarrBuilding()
 * @method static int|DBClientFile GarrBuildingDoodadSet()
 * @method static int|DBClientFile GarrBuildingPlotInst()
 * @method static int|DBClientFile GarrClassSpec()
 * @method static int|DBClientFile GarrClassSpecPlayerCond()
 * @method static int|DBClientFile GarrEncounter()
 * @method static int|DBClientFile GarrEncounterSetXEncounter()
 * @method static int|DBClientFile GarrEncounterXMechanic()
 * @method static int|DBClientFile GarrFollItemSetMember()
 * @method static int|DBClientFile GarrFollSupportSpell()
 * @method static int|DBClientFile GarrFollower()
 * @method static int|DBClientFile GarrFollowerLevelXP()
 * @method static int|DBClientFile GarrFollowerQuality()
 * @method static int|DBClientFile GarrFollowerSetXFollower()
 * @method static int|DBClientFile GarrFollowerType()
 * @method static int|DBClientFile GarrFollowerUICreature()
 * @method static int|DBClientFile GarrFollowerXAbility()
 * @method static int|DBClientFile GarrItemLevelUpgradeData()
 * @method static int|DBClientFile GarrMechanic()
 * @method static int|DBClientFile GarrMechanicSetXMechanic()
 * @method static int|DBClientFile GarrMechanicType()
 * @method static int|DBClientFile GarrMission()
 * @method static int|DBClientFile GarrMissionSet()
 * @method static int|DBClientFile GarrMissionTexture()
 * @method static int|DBClientFile GarrMissionType()
 * @method static int|DBClientFile GarrMissionXEncounter()
 * @method static int|DBClientFile GarrMissionXFollower()
 * @method static int|DBClientFile GarrMssnBonusAbility()
 * @method static int|DBClientFile GarrPlot()
 * @method static int|DBClientFile GarrPlotBuilding()
 * @method static int|DBClientFile GarrPlotInstance()
 * @method static int|DBClientFile GarrPlotUICategory()
 * @method static int|DBClientFile GarrSiteLevel()
 * @method static int|DBClientFile GarrSiteLevelPlotInst()
 * @method static int|DBClientFile GarrSpecialization()
 * @method static int|DBClientFile GarrString()
 * @method static int|DBClientFile GarrTalTreeXGarrTalResearch()
 * @method static int|DBClientFile GarrTalent()
 * @method static int|DBClientFile GarrTalentCost()
 * @method static int|DBClientFile GarrTalentMapPOI()
 * @method static int|DBClientFile GarrTalentRank()
 * @method static int|DBClientFile GarrTalentResearch()
 * @method static int|DBClientFile GarrTalentSocketProperties()
 * @method static int|DBClientFile GarrTalentTree()
 * @method static int|DBClientFile GarrType()
 * @method static int|DBClientFile GarrUiAnimClassInfo()
 * @method static int|DBClientFile GarrUiAnimRaceInfo()
 * @method static int|DBClientFile GemProperties()
 * @method static int|DBClientFile GlobalCurve()
 * @method static int|DBClientFile GlobalGameContentTuning()
 * @method static int|DBClientFile GlobalPlayerCondition()
 * @method static int|DBClientFile GlobalPlayerConditionSet()
 * @method static int|DBClientFile GlobalStrings()
 * @method static int|DBClientFile GlyphBindableSpell()
 * @method static int|DBClientFile GlyphExclusiveCategory()
 * @method static int|DBClientFile GlyphProperties()
 * @method static int|DBClientFile GlyphRequiredSpec()
 * @method static int|DBClientFile GossipXUIDisplayInfo()
 * @method static int|DBClientFile GradientEffect()
 * @method static int|DBClientFile GroundEffectDoodad()
 * @method static int|DBClientFile GroundEffectTexture()
 * @method static int|DBClientFile GroupFinderActivity()
 * @method static int|DBClientFile GroupFinderActivityGrp()
 * @method static int|DBClientFile GroupFinderActivityXPvpBracket()
 * @method static int|DBClientFile GroupFinderCategory()
 * @method static int|DBClientFile GuildColorBackground()
 * @method static int|DBClientFile GuildColorBorder()
 * @method static int|DBClientFile GuildColorEmblem()
 * @method static int|DBClientFile GuildEmblem()
 * @method static int|DBClientFile GuildPerkSpells()
 * @method static int|DBClientFile GuildShirtBackground()
 * @method static int|DBClientFile GuildShirtBorder()
 * @method static int|DBClientFile GuildTabardBackground()
 * @method static int|DBClientFile GuildTabardBorder()
 * @method static int|DBClientFile GuildTabardEmblem()
 * @method static int|DBClientFile Heirloom()
 * @method static int|DBClientFile HelmetAnimScaling()
 * @method static int|DBClientFile HelmetGeosetData()
 * @method static int|DBClientFile HighlightColor()
 * @method static int|DBClientFile HolidayDescriptions()
 * @method static int|DBClientFile HolidayNames()
 * @method static int|DBClientFile Holidays()
 * @method static int|DBClientFile Hotfixes()
 * @method static int|DBClientFile ImportPriceArmor()
 * @method static int|DBClientFile ImportPriceQuality()
 * @method static int|DBClientFile ImportPriceShield()
 * @method static int|DBClientFile ImportPriceWeapon()
 * @method static int|DBClientFile InvasionClientData()
 * @method static int|DBClientFile Item()
 * @method static int|DBClientFile ItemAppearance()
 * @method static int|DBClientFile ItemAppearanceXUiCamera()
 * @method static int|DBClientFile ItemArmorQuality()
 * @method static int|DBClientFile ItemArmorShield()
 * @method static int|DBClientFile ItemArmorTotal()
 * @method static int|DBClientFile ItemBagFamily()
 * @method static int|DBClientFile ItemBonus()
 * @method static int|DBClientFile ItemBonusList()
 * @method static int|DBClientFile ItemBonusListGroup()
 * @method static int|DBClientFile ItemBonusListGroupEntry()
 * @method static int|DBClientFile ItemBonusListLevelDelta()
 * @method static int|DBClientFile ItemBonusListWarforgeLevelDelta()
 * @method static int|DBClientFile ItemBonusSequenceSpell()
 * @method static int|DBClientFile ItemBonusTree()
 * @method static int|DBClientFile ItemBonusTreeNode()
 * @method static int|DBClientFile ItemChildEquipment()
 * @method static int|DBClientFile ItemClass()
 * @method static int|DBClientFile ItemContextPickerEntry()
 * @method static int|DBClientFile ItemCurrencyCost()
 * @method static int|DBClientFile ItemCurrencyValue()
 * @method static int|DBClientFile ItemDamageAmmo()
 * @method static int|DBClientFile ItemDamageOneHand()
 * @method static int|DBClientFile ItemDamageOneHandCaster()
 * @method static int|DBClientFile ItemDamageTwoHand()
 * @method static int|DBClientFile ItemDamageTwoHandCaster()
 * @method static int|DBClientFile ItemDisenchantLoot()
 * @method static int|DBClientFile ItemDisplayInfo()
 * @method static int|DBClientFile ItemDisplayInfoMaterialRes()
 * @method static int|DBClientFile ItemDisplayXUiCamera()
 * @method static int|DBClientFile ItemEffect()
 * @method static int|DBClientFile ItemExtendedCost()
 * @method static int|DBClientFile ItemFallbackVisual()
 * @method static int|DBClientFile ItemGroupSounds()
 * @method static int|DBClientFile ItemLevelSelector()
 * @method static int|DBClientFile ItemLevelSelectorQuality()
 * @method static int|DBClientFile ItemLevelSelectorQualitySet()
 * @method static int|DBClientFile ItemLimitCategory()
 * @method static int|DBClientFile ItemLimitCategoryCondition()
 * @method static int|DBClientFile ItemModifiedAppearance()
 * @method static int|DBClientFile ItemModifiedAppearanceExtra()
 * @method static int|DBClientFile ItemNameDescription()
 * @method static int|DBClientFile ItemNameSlotOverride()
 * @method static int|DBClientFile ItemPetFood()
 * @method static int|DBClientFile ItemPriceBase()
 * @method static int|DBClientFile ItemRangedDisplayInfo()
 * @method static int|DBClientFile ItemSearchName()
 * @method static int|DBClientFile ItemSet()
 * @method static int|DBClientFile ItemSetSpell()
 * @method static int|DBClientFile ItemSparse()
 * @method static int|DBClientFile ItemSpec()
 * @method static int|DBClientFile ItemSpecOverride()
 * @method static int|DBClientFile ItemSubClass()
 * @method static int|DBClientFile ItemSubClassMask()
 * @method static int|DBClientFile ItemVisuals()
 * @method static int|DBClientFile ItemVisualsXEffect()
 * @method static int|DBClientFile ItemXBonusTree()
 * @method static int|DBClientFile ItemXItemEffect()
 * @method static int|DBClientFile JournalEncounter()
 * @method static int|DBClientFile JournalEncounterCreature()
 * @method static int|DBClientFile JournalEncounterItem()
 * @method static int|DBClientFile JournalEncounterSection()
 * @method static int|DBClientFile JournalEncounterXDifficulty()
 * @method static int|DBClientFile JournalEncounterXMapLoc()
 * @method static int|DBClientFile JournalInstance()
 * @method static int|DBClientFile JournalItemXDifficulty()
 * @method static int|DBClientFile JournalSectionXDifficulty()
 * @method static int|DBClientFile JournalTier()
 * @method static int|DBClientFile JournalTierXInstance()
 * @method static int|DBClientFile Keychain()
 * @method static int|DBClientFile KeystoneAffix()
 * @method static int|DBClientFile LFGDungeonGroup()
 * @method static int|DBClientFile LFGDungeons()
 * @method static int|DBClientFile LFGRoleRequirement()
 * @method static int|DBClientFile LabelXContentRestrictRuleSet()
 * @method static int|DBClientFile LanguageWords()
 * @method static int|DBClientFile Languages()
 * @method static int|DBClientFile LfgDungeonsGroupingMap()
 * @method static int|DBClientFile Light()
 * @method static int|DBClientFile LightData()
 * @method static int|DBClientFile LightParams()
 * @method static int|DBClientFile LightSkybox()
 * @method static int|DBClientFile Lightning()
 * @method static int|DBClientFile LiquidMaterial()
 * @method static int|DBClientFile LiquidObject()
 * @method static int|DBClientFile LiquidType()
 * @method static int|DBClientFile LiquidTypeXTexture()
 * @method static int|DBClientFile LoadingScreenSkin()
 * @method static int|DBClientFile LoadingScreenTaxiSplines()
 * @method static int|DBClientFile LoadingScreens()
 * @method static int|DBClientFile Locale()
 * @method static int|DBClientFile Location()
 * @method static int|DBClientFile Lock()
 * @method static int|DBClientFile LockType()
 * @method static int|DBClientFile LookAtController()
 * @method static int|DBClientFile LoreText()
 * @method static int|DBClientFile LoreTextPublic()
 * @method static int|DBClientFile MCRSlotXMCRCategory()
 * @method static int|DBClientFile MailTemplate()
 * @method static int|DBClientFile ManagedWorldState()
 * @method static int|DBClientFile ManagedWorldStateBuff()
 * @method static int|DBClientFile ManagedWorldStateInput()
 * @method static int|DBClientFile ManifestInterfaceActionIcon()
 * @method static int|DBClientFile ManifestInterfaceData()
 * @method static int|DBClientFile ManifestInterfaceItemIcon()
 * @method static int|DBClientFile ManifestInterfaceTOCData()
 * @method static int|DBClientFile Map()
 * @method static int|DBClientFile MapCelestialBody()
 * @method static int|DBClientFile MapChallengeMode()
 * @method static int|DBClientFile MapDifficulty()
 * @method static int|DBClientFile MapDifficultyXCondition()
 * @method static int|DBClientFile MapLoadingScreen()
 * @method static int|DBClientFile MarketingPromotionsXLocale()
 * @method static int|DBClientFile Material()
 * @method static int|DBClientFile MawPower()
 * @method static int|DBClientFile MawPowerRarity()
 * @method static int|DBClientFile MinorTalent()
 * @method static int|DBClientFile MissileTargeting()
 * @method static int|DBClientFile ModelAnimCloakDampening()
 * @method static int|DBClientFile ModelFileData()
 * @method static int|DBClientFile ModelRibbonQuality()
 * @method static int|DBClientFile ModifiedCraftingCategory()
 * @method static int|DBClientFile ModifiedCraftingReagentItem()
 * @method static int|DBClientFile ModifiedCraftingReagentSlot()
 * @method static int|DBClientFile ModifiedCraftingSpellSlot()
 * @method static int|DBClientFile ModifiedReagentItem()
 * @method static int|DBClientFile ModifierTree()
 * @method static int|DBClientFile Mount()
 * @method static int|DBClientFile MountCapability()
 * @method static int|DBClientFile MountEquipment()
 * @method static int|DBClientFile MountType()
 * @method static int|DBClientFile MountTypeXCapability()
 * @method static int|DBClientFile MountXDisplay()
 * @method static int|DBClientFile MountXSpellVisualKitPicker()
 * @method static int|DBClientFile Movie()
 * @method static int|DBClientFile MovieFileData()
 * @method static int|DBClientFile MovieVariation()
 * @method static int|DBClientFile MultiStateProperties()
 * @method static int|DBClientFile MultiTransitionProperties()
 * @method static int|DBClientFile MythicPlusSeason()
 * @method static int|DBClientFile MythicPlusSeasonRewardLevels()
 * @method static int|DBClientFile MythicPlusSeasonTrackedAffix()
 * @method static int|DBClientFile NPCModelItemSlotDisplayInfo()
 * @method static int|DBClientFile NPCSounds()
 * @method static int|DBClientFile NameGen()
 * @method static int|DBClientFile NamesProfanity()
 * @method static int|DBClientFile NamesReserved()
 * @method static int|DBClientFile NamesReservedLocale()
 * @method static int|DBClientFile NumTalentsAtLevel()
 * @method static int|DBClientFile ObjectEffect()
 * @method static int|DBClientFile ObjectEffectModifier()
 * @method static int|DBClientFile ObjectEffectPackageElem()
 * @method static int|DBClientFile Occluder()
 * @method static int|DBClientFile OccluderCurtain()
 * @method static int|DBClientFile OccluderLocation()
 * @method static int|DBClientFile OccluderNode()
 * @method static int|DBClientFile OutlineEffect()
 * @method static int|DBClientFile OverrideSpellData()
 * @method static int|DBClientFile PVPBracketTypes()
 * @method static int|DBClientFile PVPDifficulty()
 * @method static int|DBClientFile PVPItem()
 * @method static int|DBClientFile PVPScoreboardCellInfo()
 * @method static int|DBClientFile PVPScoreboardColumnHeader()
 * @method static int|DBClientFile PVPScoreboardLayout()
 * @method static int|DBClientFile PVPStat()
 * @method static int|DBClientFile PageTextMaterial()
 * @method static int|DBClientFile PaperDollItemFrame()
 * @method static int|DBClientFile ParagonReputation()
 * @method static int|DBClientFile ParticleColor()
 * @method static int|DBClientFile Particulate()
 * @method static int|DBClientFile ParticulateSound()
 * @method static int|DBClientFile Path()
 * @method static int|DBClientFile PathEdge()
 * @method static int|DBClientFile PathNode()
 * @method static int|DBClientFile PathNodeProperty()
 * @method static int|DBClientFile PathProperty()
 * @method static int|DBClientFile Phase()
 * @method static int|DBClientFile PhaseShiftZoneSounds()
 * @method static int|DBClientFile PhaseXPhaseGroup()
 * @method static int|DBClientFile PlayerCondition()
 * @method static int|DBClientFile Positioner()
 * @method static int|DBClientFile PositionerState()
 * @method static int|DBClientFile PositionerStateEntry()
 * @method static int|DBClientFile PowerDisplay()
 * @method static int|DBClientFile PowerType()
 * @method static int|DBClientFile PrestigeLevelInfo()
 * @method static int|DBClientFile PvpBrawl()
 * @method static int|DBClientFile PvpScalingEffect()
 * @method static int|DBClientFile PvpScalingEffectType()
 * @method static int|DBClientFile PvpSeason()
 * @method static int|DBClientFile PvpSeasonRewardLevels()
 * @method static int|DBClientFile PvpTalent()
 * @method static int|DBClientFile PvpTalentCategory()
 * @method static int|DBClientFile PvpTalentSlotUnlock()
 * @method static int|DBClientFile PvpTier()
 * @method static int|DBClientFile QuestFactionReward()
 * @method static int|DBClientFile QuestFeedbackEffect()
 * @method static int|DBClientFile QuestInfo()
 * @method static int|DBClientFile QuestLine()
 * @method static int|DBClientFile QuestLineXQuest()
 * @method static int|DBClientFile QuestMoneyReward()
 * @method static int|DBClientFile QuestObjective()
 * @method static int|DBClientFile QuestPOIBlob()
 * @method static int|DBClientFile QuestPOIPoint()
 * @method static int|DBClientFile QuestPackageItem()
 * @method static int|DBClientFile QuestSort()
 * @method static int|DBClientFile QuestV2()
 * @method static int|DBClientFile QuestV2CliTask()
 * @method static int|DBClientFile QuestXGroupActivity()
 * @method static int|DBClientFile QuestXP()
 * @method static int|DBClientFile QuestXUIQuestDetailsTheme()
 * @method static int|DBClientFile QuestXUiWidgetSet()
 * @method static int|DBClientFile RTPC()
 * @method static int|DBClientFile RTPCData()
 * @method static int|DBClientFile RafActivity()
 * @method static int|DBClientFile RandPropPoints()
 * @method static int|DBClientFile RecipeProgressionGroupEntry()
 * @method static int|DBClientFile RelicSlotTierRequirement()
 * @method static int|DBClientFile RelicTalent()
 * @method static int|DBClientFile RenownRewards()
 * @method static int|DBClientFile ResearchBranch()
 * @method static int|DBClientFile ResearchField()
 * @method static int|DBClientFile ResearchProject()
 * @method static int|DBClientFile ResearchSite()
 * @method static int|DBClientFile Resistances()
 * @method static int|DBClientFile RewardPack()
 * @method static int|DBClientFile RewardPackXCurrencyType()
 * @method static int|DBClientFile RewardPackXItem()
 * @method static int|DBClientFile RibbonQuality()
 * @method static int|DBClientFile RopeEffect()
 * @method static int|DBClientFile RuneforgeLegendaryAbility()
 * @method static int|DBClientFile SDReplacementModel()
 * @method static int|DBClientFile SSAOSettings()
 * @method static int|DBClientFile Scenario()
 * @method static int|DBClientFile ScenarioEventEntry()
 * @method static int|DBClientFile ScenarioStep()
 * @method static int|DBClientFile SceneScript()
 * @method static int|DBClientFile SceneScriptGlobalText()
 * @method static int|DBClientFile SceneScriptPackage()
 * @method static int|DBClientFile SceneScriptPackageMember()
 * @method static int|DBClientFile SceneScriptText()
 * @method static int|DBClientFile ScheduledInterval()
 * @method static int|DBClientFile ScreenEffect()
 * @method static int|DBClientFile ScreenEffectType()
 * @method static int|DBClientFile ScreenLocation()
 * @method static int|DBClientFile SeamlessSite()
 * @method static int|DBClientFile ServerMessages()
 * @method static int|DBClientFile ShadowyEffect()
 * @method static int|DBClientFile SiegeableProperties()
 * @method static int|DBClientFile SkillLine()
 * @method static int|DBClientFile SkillLineAbility()
 * @method static int|DBClientFile SkillRaceClassInfo()
 * @method static int|DBClientFile SkySceneXPlayerCondition()
 * @method static int|DBClientFile Soulbind()
 * @method static int|DBClientFile SoulbindConduit()
 * @method static int|DBClientFile SoulbindConduitEnhancedSocket()
 * @method static int|DBClientFile SoulbindConduitItem()
 * @method static int|DBClientFile SoulbindConduitRank()
 * @method static int|DBClientFile SoulbindConduitRankProperties()
 * @method static int|DBClientFile SoulbindUIDisplayInfo()
 * @method static int|DBClientFile SoundAmbience()
 * @method static int|DBClientFile SoundAmbienceFlavor()
 * @method static int|DBClientFile SoundBus()
 * @method static int|DBClientFile SoundBusOverride()
 * @method static int|DBClientFile SoundEmitterPillPoints()
 * @method static int|DBClientFile SoundEmitters()
 * @method static int|DBClientFile SoundEnvelope()
 * @method static int|DBClientFile SoundFilter()
 * @method static int|DBClientFile SoundFilterElem()
 * @method static int|DBClientFile SoundKit()
 * @method static int|DBClientFile SoundKitAdvanced()
 * @method static int|DBClientFile SoundKitChild()
 * @method static int|DBClientFile SoundKitEntry()
 * @method static int|DBClientFile SoundKitFallback()
 * @method static int|DBClientFile SoundOverride()
 * @method static int|DBClientFile SoundParameter()
 * @method static int|DBClientFile SoundProviderPreferences()
 * @method static int|DBClientFile SourceInfo()
 * @method static int|DBClientFile SpamMessages()
 * @method static int|DBClientFile SpecSetMember()
 * @method static int|DBClientFile SpecializationSpells()
 * @method static int|DBClientFile SpecializationSpellsDisplay()
 * @method static int|DBClientFile Spell()
 * @method static int|DBClientFile SpellActionBarPref()
 * @method static int|DBClientFile SpellActivationOverlay()
 * @method static int|DBClientFile SpellAuraOptions()
 * @method static int|DBClientFile SpellAuraRestrictions()
 * @method static int|DBClientFile SpellAuraVisXChrSpec()
 * @method static int|DBClientFile SpellAuraVisibility()
 * @method static int|DBClientFile SpellCastTimes()
 * @method static int|DBClientFile SpellCastingRequirements()
 * @method static int|DBClientFile SpellCategories()
 * @method static int|DBClientFile SpellCategory()
 * @method static int|DBClientFile SpellChainEffects()
 * @method static int|DBClientFile SpellClassOptions()
 * @method static int|DBClientFile SpellClutterAreaEffectCounts()
 * @method static int|DBClientFile SpellClutterFrameRates()
 * @method static int|DBClientFile SpellClutterImpactModelCounts()
 * @method static int|DBClientFile SpellClutterKitDistances()
 * @method static int|DBClientFile SpellClutterMissileDist()
 * @method static int|DBClientFile SpellClutterWeaponTrailDist()
 * @method static int|DBClientFile SpellCooldowns()
 * @method static int|DBClientFile SpellDescriptionVariables()
 * @method static int|DBClientFile SpellDispelType()
 * @method static int|DBClientFile SpellDuration()
 * @method static int|DBClientFile SpellEffect()
 * @method static int|DBClientFile SpellEffectAutoDescription()
 * @method static int|DBClientFile SpellEffectEmission()
 * @method static int|DBClientFile SpellEquippedItems()
 * @method static int|DBClientFile SpellFlyout()
 * @method static int|DBClientFile SpellFlyoutItem()
 * @method static int|DBClientFile SpellFocusObject()
 * @method static int|DBClientFile SpellInterrupts()
 * @method static int|DBClientFile SpellItemEnchantment()
 * @method static int|DBClientFile SpellItemEnchantmentCondition()
 * @method static int|DBClientFile SpellKeyboundOverride()
 * @method static int|DBClientFile SpellLabel()
 * @method static int|DBClientFile SpellLearnSpell()
 * @method static int|DBClientFile SpellLevels()
 * @method static int|DBClientFile SpellMechanic()
 * @method static int|DBClientFile SpellMisc()
 * @method static int|DBClientFile SpellMissile()
 * @method static int|DBClientFile SpellMissileMotion()
 * @method static int|DBClientFile SpellName()
 * @method static int|DBClientFile SpellOverrideName()
 * @method static int|DBClientFile SpellPower()
 * @method static int|DBClientFile SpellPowerDifficulty()
 * @method static int|DBClientFile SpellProceduralEffect()
 * @method static int|DBClientFile SpellProcsPerMinute()
 * @method static int|DBClientFile SpellProcsPerMinuteMod()
 * @method static int|DBClientFile SpellRadius()
 * @method static int|DBClientFile SpellRange()
 * @method static int|DBClientFile SpellReagents()
 * @method static int|DBClientFile SpellReagentsCurrency()
 * @method static int|DBClientFile SpellScaling()
 * @method static int|DBClientFile SpellScript()
 * @method static int|DBClientFile SpellScriptText()
 * @method static int|DBClientFile SpellShapeshift()
 * @method static int|DBClientFile SpellShapeshiftForm()
 * @method static int|DBClientFile SpellSpecialUnitEffect()
 * @method static int|DBClientFile SpellTargetRestrictions()
 * @method static int|DBClientFile SpellTotems()
 * @method static int|DBClientFile SpellVisual()
 * @method static int|DBClientFile SpellVisualAnim()
 * @method static int|DBClientFile SpellVisualColorEffect()
 * @method static int|DBClientFile SpellVisualEffectName()
 * @method static int|DBClientFile SpellVisualEvent()
 * @method static int|DBClientFile SpellVisualKit()
 * @method static int|DBClientFile SpellVisualKitAreaModel()
 * @method static int|DBClientFile SpellVisualKitEffect()
 * @method static int|DBClientFile SpellVisualKitModelAttach()
 * @method static int|DBClientFile SpellVisualKitPicker()
 * @method static int|DBClientFile SpellVisualKitPickerEntry()
 * @method static int|DBClientFile SpellVisualMissile()
 * @method static int|DBClientFile SpellVisualScreenEffect()
 * @method static int|DBClientFile SpellXDescriptionVariables()
 * @method static int|DBClientFile SpellXSpellVisual()
 * @method static int|DBClientFile StartupFiles()
 * @method static int|DBClientFile Startup_Strings()
 * @method static int|DBClientFile Stationery()
 * @method static int|DBClientFile SummonProperties()
 * @method static int|DBClientFile TactKey()
 * @method static int|DBClientFile TactKeyLookup()
 * @method static int|DBClientFile Talent()
 * @method static int|DBClientFile TaxiNodes()
 * @method static int|DBClientFile TaxiPath()
 * @method static int|DBClientFile TaxiPathNode()
 * @method static int|DBClientFile TerrainColorGradingRamp()
 * @method static int|DBClientFile TerrainMaterial()
 * @method static int|DBClientFile TerrainType()
 * @method static int|DBClientFile TerrainTypeSounds()
 * @method static int|DBClientFile TextureBlendSet()
 * @method static int|DBClientFile TextureFileData()
 * @method static int|DBClientFile TierTransition()
 * @method static int|DBClientFile TotemCategory()
 * @method static int|DBClientFile Toy()
 * @method static int|DBClientFile TradeSkillCategory()
 * @method static int|DBClientFile TradeSkillItem()
 * @method static int|DBClientFile TransformMatrix()
 * @method static int|DBClientFile TransmogDefaultLevel()
 * @method static int|DBClientFile TransmogHoliday()
 * @method static int|DBClientFile TransmogIllusion()
 * @method static int|DBClientFile TransmogSet()
 * @method static int|DBClientFile TransmogSetGroup()
 * @method static int|DBClientFile TransmogSetItem()
 * @method static int|DBClientFile TransportAnimation()
 * @method static int|DBClientFile TransportPhysics()
 * @method static int|DBClientFile TransportRotation()
 * @method static int|DBClientFile Trophy()
 * @method static int|DBClientFile UIChromieTimeExpansionInfo()
 * @method static int|DBClientFile UICovenantAbility()
 * @method static int|DBClientFile UICovenantPreview()
 * @method static int|DBClientFile UIDungeonScoreRarity()
 * @method static int|DBClientFile UIEventToast()
 * @method static int|DBClientFile UIExpansionDisplayInfo()
 * @method static int|DBClientFile UIExpansionDisplayInfoIcon()
 * @method static int|DBClientFile UIScriptedAnimationEffect()
 * @method static int|DBClientFile UISplashScreen()
 * @method static int|DBClientFile UiCamFbackTransmogChrRace()
 * @method static int|DBClientFile UiCamFbackTransmogWeapon()
 * @method static int|DBClientFile UiCamera()
 * @method static int|DBClientFile UiCameraType()
 * @method static int|DBClientFile UiCanvas()
 * @method static int|DBClientFile UiCovenantDisplayInfo()
 * @method static int|DBClientFile UiItemInteraction()
 * @method static int|DBClientFile UiMap()
 * @method static int|DBClientFile UiMapArt()
 * @method static int|DBClientFile UiMapArtStyleLayer()
 * @method static int|DBClientFile UiMapArtTile()
 * @method static int|DBClientFile UiMapAssignment()
 * @method static int|DBClientFile UiMapFogOfWar()
 * @method static int|DBClientFile UiMapFogOfWarVisualization()
 * @method static int|DBClientFile UiMapGroupMember()
 * @method static int|DBClientFile UiMapLink()
 * @method static int|DBClientFile UiMapXMapArt()
 * @method static int|DBClientFile UiModelScene()
 * @method static int|DBClientFile UiModelSceneActor()
 * @method static int|DBClientFile UiModelSceneActorDisplay()
 * @method static int|DBClientFile UiModelSceneCamera()
 * @method static int|DBClientFile UiPartyPose()
 * @method static int|DBClientFile UiQuestDetailsTheme()
 * @method static int|DBClientFile UiTextureAtlas()
 * @method static int|DBClientFile UiTextureAtlasElement()
 * @method static int|DBClientFile UiTextureAtlasMember()
 * @method static int|DBClientFile UiTextureKit()
 * @method static int|DBClientFile UiWidget()
 * @method static int|DBClientFile UiWidgetConstantSource()
 * @method static int|DBClientFile UiWidgetDataSource()
 * @method static int|DBClientFile UiWidgetMap()
 * @method static int|DBClientFile UiWidgetSet()
 * @method static int|DBClientFile UiWidgetStringSource()
 * @method static int|DBClientFile UiWidgetVisTypeDataReq()
 * @method static int|DBClientFile UiWidgetVisualization()
 * @method static int|DBClientFile UiWidgetXWidgetSet()
 * @method static int|DBClientFile UnitBlood()
 * @method static int|DBClientFile UnitBloodLevels()
 * @method static int|DBClientFile UnitCondition()
 * @method static int|DBClientFile UnitPowerBar()
 * @method static int|DBClientFile Vehicle()
 * @method static int|DBClientFile VehiclePOIType()
 * @method static int|DBClientFile VehicleSeat()
 * @method static int|DBClientFile VehicleUIIndSeat()
 * @method static int|DBClientFile VehicleUIIndicator()
 * @method static int|DBClientFile Vignette()
 * @method static int|DBClientFile VirtualAttachment()
 * @method static int|DBClientFile VirtualAttachmentCustomization()
 * @method static int|DBClientFile VocalUISounds()
 * @method static int|DBClientFile VolumeFogCondition()
 * @method static int|DBClientFile WMOAreaTable()
 * @method static int|DBClientFile WMOMinimapTexture()
 * @method static int|DBClientFile WaterfallData()
 * @method static int|DBClientFile WaypointEdge()
 * @method static int|DBClientFile WaypointNode()
 * @method static int|DBClientFile WaypointSafeLocs()
 * @method static int|DBClientFile WbAccessControlList()
 * @method static int|DBClientFile WbCertWhitelist()
 * @method static int|DBClientFile WeaponImpactSounds()
 * @method static int|DBClientFile WeaponSwingSounds2()
 * @method static int|DBClientFile WeaponTrail()
 * @method static int|DBClientFile WeaponTrailModelDef()
 * @method static int|DBClientFile WeaponTrailParam()
 * @method static int|DBClientFile Weather()
 * @method static int|DBClientFile WeatherXParticulate()
 * @method static int|DBClientFile WeeklyRewardChestThreshold()
 * @method static int|DBClientFile WindSettings()
 * @method static int|DBClientFile WorldBossLockout()
 * @method static int|DBClientFile WorldChunkSounds()
 * @method static int|DBClientFile WorldEffect()
 * @method static int|DBClientFile WorldElapsedTimer()
 * @method static int|DBClientFile WorldMapOverlay()
 * @method static int|DBClientFile WorldMapOverlayTile()
 * @method static int|DBClientFile WorldStateExpression()
 * @method static int|DBClientFile WorldStateZoneSounds()
 * @method static int|DBClientFile World_PVP_Area()
 * @method static int|DBClientFile ZoneIntroMusicTable()
 * @method static int|DBClientFile ZoneLight()
 * @method static int|DBClientFile ZoneLightPoint()
 * @method static int|DBClientFile ZoneMusic()
 * @method static int|DBClientFile ZoneStory()
 */
class DBClientFile extends Enum
{
    private const Achievement                     = 1260179;
    private const Achievement_Category            = 1324299;
    private const AdventureJournal                = 1115949;
    private const AdventureMapPOI                 = 1267070;
    private const AlliedRace                      = 1710672;
    private const AnimKit                         = 1304323;
    private const AnimKitBoneSet                  = 1375433;
    private const AnimKitBoneSetAlias             = 1266937;
    private const AnimKitConfig                   = 1300872;
    private const AnimKitConfigBoneSet            = 1300873;
    private const AnimKitPriority                 = 1266540;
    private const AnimKitReplacement              = 1559807;
    private const AnimKitSegment                  = 1304324;
    private const AnimReplacement                 = 1301100;
    private const AnimReplacementSet              = 1284817;
    private const AnimaCable                      = 3286805;
    private const AnimaCylinder                   = 3286804;
    private const AnimaMaterial                   = 3153990;
    private const AnimationData                   = 1375431;
    private const AreaConditionalData             = 2123730;
    private const AreaFarClipOverride             = 1537162;
    private const AreaGroupMember                 = 1093406;
    private const AreaPOI                         = 1000630;
    private const AreaPOIState                    = 1000631;
    private const AreaTable                       = 1353545;
    private const AreaTrigger                     = 1354401;
    private const AreaTriggerActionSet            = 1352378;
    private const AreaTriggerBox                  = 1332554;
    private const AreaTriggerCreateProperties     = 1937227;
    private const AreaTriggerCylinder             = 1121943;
    private const AreaTriggerSphere               = 1315630;
    private const ArenaCcItem                     = 3849793;
    private const ArmorLocation                   = 1284818;
    private const Artifact                        = 1007934;
    private const ArtifactAppearance              = 1116407;
    private const ArtifactAppearanceSet           = 1116408;
    private const ArtifactCategory                = 1376210;
    private const ArtifactItemToTransmog          = 2029780;
    private const ArtifactPower                   = 1007937;
    private const ArtifactPowerLink               = 1133731;
    private const ArtifactPowerPicker             = 1597467;
    private const ArtifactPowerRank               = 1261405;
    private const ArtifactQuestXP                 = 1036203;
    private const ArtifactTier                    = 1600114;
    private const ArtifactUnlock                  = 1094540;
    private const AuctionHouse                    = 1237439;
    private const AzeriteEmpoweredItem            = 1846046;
    private const AzeriteEssence                  = 2829665;
    private const AzeriteEssencePower             = 2829666;
    private const AzeriteItem                     = 1846048;
    private const AzeriteItemMilestonePower       = 1915395;
    private const AzeriteKnowledgeMultiplier      = 3148050;
    private const AzeriteLevelInfo                = 3147968;
    private const AzeritePower                    = 1846044;
    private const AzeritePowerSetMember           = 1846040;
    private const AzeriteTierUnlock               = 1846043;
    private const AzeriteTierUnlockSet            = 2446322;
    private const AzeriteUnlockMapping            = 2564314;
    private const BankBagSlotPrices               = 1284819;
    private const BannedAddons                    = 1373459;
    private const BarberShopStyle                 = 1237437;
    private const BarrageEffect                   = 2499852;
    private const BattlePetAbility                = 841610;
    private const BattlePetAbilityEffect          = 801575;
    private const BattlePetAbilityState           = 801576;
    private const BattlePetAbilityTurn            = 801577;
    private const BattlePetBreedQuality           = 801578;
    private const BattlePetBreedState             = 801579;
    private const BattlePetDisplayOverride        = 1802988;
    private const BattlePetEffectProperties       = 801580;
    private const BattlePetNPCTeamMember          = 841648;
    private const BattlePetSpecies                = 841622;
    private const BattlePetSpeciesState           = 801581;
    private const BattlePetSpeciesXAbility        = 801582;
    private const BattlePetSpeciesXCovenant       = 3669304;
    private const BattlePetState                  = 801583;
    private const BattlePetVisual                 = 801584;
    private const BattlemasterList                = 1360265;
    private const BeamEffect                      = 1525607;
    private const BoneWindModifierModel           = 1467254;
    private const BoneWindModifiers               = 1416756;
    private const BonusRoll                       = 1983274;
    private const Bounty                          = 1367866;
    private const BountySet                       = 1367865;
    private const BroadcastText                   = 841604;
    private const BroadcastTextDuration           = 2166900;
    private const CameraEffect                    = 1117695;
    private const CameraEffectEntry               = 1117696;
    private const CameraMode                      = 1343308;
    private const Campaign                        = 2031607;
    private const CampaignXCondition              = 2031611;
    private const CampaignXQuestLine              = 2036722;
    private const CastableRaidBuffs               = 1283018;
    private const CelestialBody                   = 1592470;
    private const Cfg_Categories                  = 1068162;
    private const Cfg_Configs                     = 1080949;
    private const Cfg_Regions                     = 1082876;
    private const ChallengeModeItemBonusOverride  = 2965645;
    private const CharBaseInfo                    = 1343386;
    private const CharBaseSection                 = 1375798;
    private const CharComponentTextureLayouts     = 1360262;
    private const CharComponentTextureSections    = 1360263;
    private const CharHairGeosets                 = 1256914;
    private const CharSectionCondition            = 2388725;
    private const CharShipment                    = 972425;
    private const CharShipmentContainer           = 972405;
    private const CharStartKit                    = 3055696;
    private const CharTitles                      = 1349054;
    private const CharacterFacialHairStyles       = 1369752;
    private const CharacterLoadout                = 1344281;
    private const CharacterLoadoutItem            = 1302846;
    private const CharacterLoadoutPet             = 3724843;
    private const CharacterServiceInfo            = 1815417;
    private const ChatChannels                    = 1345278;
    private const ChatProfanity                   = 1117084;
    private const ChrClassRaceSex                 = 1306188;
    private const ChrClassTitle                   = 1267497;
    private const ChrClassUIChrModelInfo          = 3754770;
    private const ChrClassUIDisplay               = 1316515;
    private const ChrClassVillain                 = 1267498;
    private const ChrClasses                      = 1361031;
    private const ChrClassesXPowerTypes           = 1121420;
    private const ChrCreateClassAnimTarget        = 3671168;
    private const ChrCreateClassAnimTargetInfo    = 3671169;
    private const ChrCustClientChoiceConversion   = 3590348;
    private const ChrCustItemGeoModify            = 3952714;
    private const ChrCustomization                = 1611874;
    private const ChrCustomizationBoneSet         = 3460181;
    private const ChrCustomizationCategory        = 3526439;
    private const ChrCustomizationChoice          = 3450554;
    private const ChrCustomizationCondModel       = 3460182;
    private const ChrCustomizationConversion      = 3463337;
    private const ChrCustomizationDisplayInfo     = 3593032;
    private const ChrCustomizationElement         = 3512765;
    private const ChrCustomizationGeoset          = 3456171;
    private const ChrCustomizationMaterial        = 3459652;
    private const ChrCustomizationOption          = 3384247;
    private const ChrCustomizationReq             = 3450453;
    private const ChrCustomizationReqChoice       = 3580359;
    private const ChrCustomizationSkinnedModel    = 3460183;
    private const ChrModel                        = 3384313;
    private const ChrModelMaterial                = 3566562;
    private const ChrModelTextureLayer            = 3548976;
    private const ChrRaceRacialAbility            = 3507821;
    private const ChrRaceXChrModel                = 3490304;
    private const ChrRaces                        = 1305311;
    private const ChrSpecialization               = 1343390;
    private const ChrUpgradeBucket                = 984529;
    private const ChrUpgradeBucketSpell           = 984528;
    private const ChrUpgradeTier                  = 984530;
    private const CinematicCamera                 = 1294214;
    private const CinematicSequences              = 1134583;
    private const ClientSceneEffect               = 1939843;
    private const CloakDampening                  = 1465903;
    private const CloneEffect                     = 2175218;
    private const CombatCondition                 = 1120958;
    private const CommentatorIndirectSpell        = 3067644;
    private const CommentatorStartLocation        = 1664251;
    private const CommentatorTrackedCooldown      = 1661584;
    private const CommunityIcon                   = 2098645;
    private const ComponentModelFileData          = 1349053;
    private const ComponentTextureFileData        = 1278239;
    private const ConditionalContentTuning        = 3501965;
    private const ConfigurationWarning            = 1709409;
    private const ContentRestrictionRuleSet       = 4281307;
    private const ContentTuning                   = 1962930;
    private const ContentTuningXExpected          = 2976765;
    private const Contribution                    = 1587153;
    private const ContributionStyle               = 2143633;
    private const ContributionStyleContainer      = 2143634;
    private const ConversationLine                = 1260801;
    private const CorruptionEffects               = 3220711;
    private const Covenant                        = 3384973;
    private const Creature                        = 841631;
    private const CreatureDifficulty              = 879282;
    private const CreatureDispXUiCamera           = 1146692;
    private const CreatureDisplayInfo             = 1108759;
    private const CreatureDisplayInfoCond         = 1332686;
    private const CreatureDisplayInfoCondXChoice  = 3670439;
    private const CreatureDisplayInfoEvt          = 1586882;
    private const CreatureDisplayInfoExtra        = 1264997;
    private const CreatureDisplayInfoGeosetData   = 1720141;
    private const CreatureDisplayInfoOption       = 3692043;
    private const CreatureDisplayInfoTrn          = 1146698;
    private const CreatureFamily                  = 1351351;
    private const CreatureImmunities              = 1131322;
    private const CreatureModelData               = 1365368;
    private const CreatureMovementInfo            = 1125666;
    private const CreatureSoundData               = 1344466;
    private const CreatureSoundFidget             = 4178576;
    private const CreatureType                    = 1131315;
    private const CreatureXContribution           = 1587158;
    private const CreatureXDisplayInfo            = 1864302;
    private const CreatureXUiWidgetSet            = 3055738;
    private const Criteria                        = 1263817;
    private const CriteriaTree                    = 1263818;
    private const CriteriaTreeXEffect             = 1345969;
    private const CurrencyCategory                = 1125667;
    private const CurrencyContainer               = 1934603;
    private const CurrencyTypes                   = 1095531;
    private const Curve                           = 892585;
    private const CurvePoint                      = 892586;
    private const DeathThudLookups                = 1279415;
    private const DecalProperties                 = 1278176;
    private const DeclinedWord                    = 1279100;
    private const DeclinedWordCases               = 1279099;
    private const DestructibleModelData           = 1122116;
    private const DeviceBlacklist                 = 922722;
    private const Difficulty                      = 1352127;
    private const DisplaySeason                   = 4279827;
    private const DissolveEffect                  = 1304325;
    private const DriverBlacklist                 = 922720;
    private const DungeonEncounter                = 1347279;
    private const DurabilityCosts                 = 1283019;
    private const DurabilityQuality               = 1130268;
    private const EdgeGlowEffect                  = 1387381;
    private const Emotes                          = 1343602;
    private const EmotesText                      = 1347273;
    private const EmotesTextData                  = 1283024;
    private const EmotesTextSound                 = 1286524;
    private const EnvironmentalDamage             = 1278398;
    private const Exhaustion                      = 1343313;
    private const ExpectedStat                    = 1937326;
    private const ExpectedStatMod                 = 1969773;
    private const ExtraAbilityInfo                = 3527889;
    private const Faction                         = 1361972;
    private const FactionGroup                    = 1343595;
    private const FactionTemplate                 = 1361579;
    private const FootprintTextures               = 1308056;
    private const FootstepTerrainLookup           = 1267647;
    private const FriendshipRepReaction           = 1237638;
    private const FriendshipReputation            = 1237639;
    private const FullScreenEffect                = 1348282;
    private const GMSurveyAnswers                 = 1283025;
    private const GMSurveyCurrentSurvey           = 1278177;
    private const GMSurveyQuestions               = 1278178;
    private const GMSurveySurveys                 = 1283020;
    private const GameClockDebug                  = 2922072;
    private const GameObjectAnimGroupMember       = 3565753;
    private const GameObjectArtKit                = 1266737;
    private const GameObjectDiffAnimMap           = 1302847;
    private const GameObjectDisplayInfo           = 1266277;
    private const GameObjectDisplayInfoXSoundKit  = 1345272;
    private const GameObjects                     = 841620;
    private const GameParameter                   = 3405438;
    private const GameTips                        = 1368021;
    private const GarrAbility                     = 966238;
    private const GarrAbilityCategory             = 1020248;
    private const GarrAbilityEffect               = 966241;
    private const GarrAutoCombatant               = 3305399;
    private const GarrAutoSpell                   = 3305400;
    private const GarrAutoSpellEffect             = 3307335;
    private const GarrBuilding                    = 929747;
    private const GarrBuildingDoodadSet           = 943937;
    private const GarrBuildingPlotInst            = 983298;
    private const GarrClassSpec                   = 981570;
    private const GarrClassSpecPlayerCond         = 1380674;
    private const GarrEncounter                   = 975304;
    private const GarrEncounterSetXEncounter      = 1354772;
    private const GarrEncounterXMechanic          = 967961;
    private const GarrFollItemSetMember           = 981569;
    private const GarrFollSupportSpell            = 1345970;
    private const GarrFollower                    = 949906;
    private const GarrFollowerLevelXP             = 970979;
    private const GarrFollowerQuality             = 1027793;
    private const GarrFollowerSetXFollower        = 1361029;
    private const GarrFollowerType                = 1118784;
    private const GarrFollowerUICreature          = 1412636;
    private const GarrFollowerXAbility            = 968468;
    private const GarrItemLevelUpgradeData        = 1572314;
    private const GarrMechanic                    = 967963;
    private const GarrMechanicSetXMechanic        = 1391531;
    private const GarrMechanicType                = 967964;
    private const GarrMission                     = 967962;
    private const GarrMissionSet                  = 3055759;
    private const GarrMissionTexture              = 1125220;
    private const GarrMissionType                 = 984174;
    private const GarrMissionXEncounter           = 967960;
    private const GarrMissionXFollower            = 1359096;
    private const GarrMssnBonusAbility            = 1138458;
    private const GarrPlot                        = 937634;
    private const GarrPlotBuilding                = 929743;
    private const GarrPlotInstance                = 929742;
    private const GarrPlotUICategory              = 937635;
    private const GarrSiteLevel                   = 939295;
    private const GarrSiteLevelPlotInst           = 940404;
    private const GarrSpecialization              = 937647;
    private const GarrString                      = 1416758;
    private const GarrTalTreeXGarrTalResearch     = 3195601;
    private const GarrTalent                      = 1361032;
    private const GarrTalentCost                  = 3514438;
    private const GarrTalentMapPOI                = 3534056;
    private const GarrTalentRank                  = 3069763;
    private const GarrTalentResearch              = 3195518;
    private const GarrTalentSocketProperties      = 3612617;
    private const GarrTalentTree                  = 1361030;
    private const GarrType                        = 1333161;
    private const GarrUiAnimClassInfo             = 976037;
    private const GarrUiAnimRaceInfo              = 976035;
    private const GemProperties                   = 1343604;
    private const GlobalCurve                     = 3752002;
    private const GlobalGameContentTuning         = 3756368;
    private const GlobalPlayerCondition           = 4082838;
    private const GlobalPlayerConditionSet        = 4082839;
    private const GlobalStrings                   = 1394440;
    private const GlyphBindableSpell              = 1270147;
    private const GlyphExclusiveCategory          = 948546;
    private const GlyphProperties                 = 1345274;
    private const GlyphRequiredSpec               = 948496;
    private const GossipXUIDisplayInfo            = 3622253;
    private const GradientEffect                  = 2433582;
    private const GroundEffectDoodad              = 1308057;
    private const GroundEffectTexture             = 1308499;
    private const GroupFinderActivity             = 974813;
    private const GroupFinderActivityGrp          = 974814;
    private const GroupFinderActivityXPvpBracket  = 4206623;
    private const GroupFinderCategory             = 974812;
    private const GuildColorBackground            = 1286526;
    private const GuildColorBorder                = 1286527;
    private const GuildColorEmblem                = 1286525;
    private const GuildEmblem                     = 2734754;
    private const GuildPerkSpells                 = 1135238;
    private const GuildShirtBackground            = 2921008;
    private const GuildShirtBorder                = 2921475;
    private const GuildTabardBackground           = 2909769;
    private const GuildTabardBorder               = 2920485;
    private const GuildTabardEmblem               = 2910470;
    private const Heirloom                        = 1097696;
    private const HelmetAnimScaling               = 1348283;
    private const HelmetGeosetData                = 2821752;
    private const HighlightColor                  = 996358;
    private const HolidayDescriptions             = 996360;
    private const HolidayNames                    = 996359;
    private const Holidays                        = 996357;
    private const Hotfixes                        = 1995523;
    private const ImportPriceArmor                = 1121229;
    private const ImportPriceQuality              = 1121228;
    private const ImportPriceShield               = 1121227;
    private const ImportPriceWeapon               = 1121230;
    private const InvasionClientData              = 1336651;
    private const Item                            = 841626;
    private const ItemAppearance                  = 982462;
    private const ItemAppearanceXUiCamera         = 1248126;
    private const ItemArmorQuality                = 1283021;
    private const ItemArmorShield                 = 1277741;
    private const ItemArmorTotal                  = 1283022;
    private const ItemBagFamily                   = 1278179;
    private const ItemBonus                       = 959070;
    private const ItemBonusList                   = 1805807;
    private const ItemBonusListGroup              = 3755382;
    private const ItemBonusListGroupEntry         = 3025306;
    private const ItemBonusListLevelDelta         = 1320358;
    private const ItemBonusListWarforgeLevelDelta = 2924997;
    private const ItemBonusSequenceSpell          = 3026822;
    private const ItemBonusTree                   = 3055768;
    private const ItemBonusTreeNode               = 987134;
    private const ItemChildEquipment              = 1247926;
    private const ItemClass                       = 1140189;
    private const ItemContextPickerEntry          = 1405665;
    private const ItemCurrencyCost                = 801670;
    private const ItemCurrencyValue               = 3755770;
    private const ItemDamageAmmo                  = 1277740;
    private const ItemDamageOneHand               = 1277743;
    private const ItemDamageOneHandCaster         = 1277739;
    private const ItemDamageTwoHand               = 1277738;
    private const ItemDamageTwoHandCaster         = 1277742;
    private const ItemDisenchantLoot              = 1134087;
    private const ItemDisplayInfo                 = 1266429;
    private const ItemDisplayInfoMaterialRes      = 1280614;
    private const ItemDisplayXUiCamera            = 1146690;
    private const ItemEffect                      = 969941;
    private const ItemExtendedCost                = 801681;
    private const ItemFallbackVisual              = 2358574;
    private const ItemGroupSounds                 = 1283023;
    private const ItemLevelSelector               = 1588911;
    private const ItemLevelSelectorQuality        = 1624937;
    private const ItemLevelSelectorQualitySet     = 1624933;
    private const ItemLimitCategory               = 1237440;
    private const ItemLimitCategoryCondition      = 1378590;
    private const ItemModifiedAppearance          = 982457;
    private const ItemModifiedAppearanceExtra     = 1278399;
    private const ItemNameDescription             = 1332559;
    private const ItemNameSlotOverride            = 3723474;
    private const ItemPetFood                     = 1302240;
    private const ItemPriceBase                   = 1121231;
    private const ItemRangedDisplayInfo           = 1270315;
    private const ItemSearchName                  = 1273408;
    private const ItemSet                         = 1343609;
    private const ItemSetSpell                    = 1314689;
    private const ItemSparse                      = 1572924;
    private const ItemSpec                        = 1135120;
    private const ItemSpecOverride                = 1134576;
    private const ItemSubClass                    = 1261604;
    private const ItemSubClassMask                = 1302852;
    private const ItemVisuals                     = 1343605;
    private const ItemVisualsXEffect              = 3043873;
    private const ItemXBonusTree                  = 987133;
    private const ItemXItemEffect                 = 3177687;
    private const JournalEncounter                = 1240336;
    private const JournalEncounterCreature        = 1301155;
    private const JournalEncounterItem            = 1344467;
    private const JournalEncounterSection         = 1134413;
    private const JournalEncounterXDifficulty     = 1121901;
    private const JournalEncounterXMapLoc         = 1722928;
    private const JournalInstance                 = 1237438;
    private const JournalItemXDifficulty          = 1277744;
    private const JournalSectionXDifficulty       = 1121900;
    private const JournalTier                     = 1349056;
    private const JournalTierXInstance            = 1285009;
    private const Keychain                        = 801693;
    private const KeystoneAffix                   = 1344761;
    private const LFGDungeonGroup                 = 1135058;
    private const LFGDungeons                     = 1361033;
    private const LFGRoleRequirement              = 982805;
    private const LabelXContentRestrictRuleSet    = 4281309;
    private const LanguageWords                   = 984702;
    private const Languages                       = 1135325;
    private const LfgDungeonsGroupingMap          = 1339818;
    private const Light                           = 1375579;
    private const LightData                       = 1375580;
    private const LightParams                     = 1334669;
    private const LightSkybox                     = 1308501;
    private const Lightning                       = 2003383;
    private const LiquidMaterial                  = 1132538;
    private const LiquidObject                    = 1308058;
    private const LiquidType                      = 1371380;
    private const LiquidTypeXTexture              = 2261065;
    private const LoadingScreenSkin               = 2478235;
    private const LoadingScreenTaxiSplines        = 1302239;
    private const LoadingScreens                  = 1266541;
    private const Locale                          = 801706;
    private const Location                        = 801707;
    private const Lock                            = 1343608;
    private const LockType                        = 1284823;
    private const LookAtController                = 1098785;
    private const LoreText                        = 3311370;
    private const LoreTextPublic                  = 3479846;
    private const MCRSlotXMCRCategory             = 3390955;
    private const MailTemplate                    = 1240344;
    private const ManagedWorldState               = 1587159;
    private const ManagedWorldStateBuff           = 1587155;
    private const ManagedWorldStateInput          = 1587151;
    private const ManifestInterfaceActionIcon     = 1375803;
    private const ManifestInterfaceData           = 1375801;
    private const ManifestInterfaceItemIcon       = 1375804;
    private const ManifestInterfaceTOCData        = 1267335;
    private const Map                             = 1349477;
    private const MapCelestialBody                = 1597466;
    private const MapChallengeMode                = 801709;
    private const MapDifficulty                   = 1367868;
    private const MapDifficultyXCondition         = 1375435;
    private const MapLoadingScreen                = 1719707;
    private const MarketingPromotionsXLocale      = 801710;
    private const Material                        = 1294217;
    private const MawPower                        = 2991315;
    private const MawPowerRarity                  = 2997952;
    private const MinorTalent                     = 1347274;
    private const MissileTargeting                = 1710117;
    private const ModelAnimCloakDampening         = 1465904;
    private const ModelFileData                   = 1337833;
    private const ModelRibbonQuality              = 1399953;
    private const ModifiedCraftingCategory        = 3386486;
    private const ModifiedCraftingReagentItem     = 3386487;
    private const ModifiedCraftingReagentSlot     = 3386488;
    private const ModifiedCraftingSpellSlot       = 3390956;
    private const ModifiedReagentItem             = 3386490;
    private const ModifierTree                    = 1267645;
    private const Mount                           = 921760;
    private const MountCapability                 = 1114709;
    private const MountEquipment                  = 2923510;
    private const MountType                       = 1114674;
    private const MountTypeXCapability            = 1114715;
    private const MountXDisplay                   = 1576117;
    private const MountXSpellVisualKitPicker      = 3989477;
    private const Movie                           = 1332556;
    private const MovieFileData                   = 1301154;
    private const MovieVariation                  = 1339819;
    private const MultiStateProperties            = 1965592;
    private const MultiTransitionProperties       = 1965589;
    private const MythicPlusSeason                = 2400282;
    private const MythicPlusSeasonRewardLevels    = 2123783;
    private const MythicPlusSeasonTrackedAffix    = 4067473;
    private const NPCModelItemSlotDisplayInfo     = 1340661;
    private const NPCSounds                       = 1282621;
    private const NameGen                         = 1122117;
    private const NamesProfanity                  = 1117086;
    private const NamesReserved                   = 1117085;
    private const NamesReservedLocale             = 1117087;
    private const NumTalentsAtLevel               = 1953326;
    private const ObjectEffect                    = 1090577;
    private const ObjectEffectModifier            = 1090575;
    private const ObjectEffectPackageElem         = 1090578;
    private const Occluder                        = 2066958;
    private const OccluderCurtain                 = 3850529;
    private const OccluderLocation                = 2115224;
    private const OccluderNode                    = 2066959;
    private const OutlineEffect                   = 1279739;
    private const OverrideSpellData               = 1002186;
    private const PVPBracketTypes                 = 1394275;
    private const PVPDifficulty                   = 1339820;
    private const PVPItem                         = 972287;
    private const PVPScoreboardCellInfo           = 2992916;
    private const PVPScoreboardColumnHeader       = 2992917;
    private const PVPScoreboardLayout             = 2992918;
    private const PVPStat                         = 2992919;
    private const PageTextMaterial                = 1271600;
    private const PaperDollItemFrame              = 1252503;
    private const ParagonReputation               = 1581183;
    private const ParticleColor                   = 1284820;
    private const Particulate                     = 3396285;
    private const ParticulateSound                = 2053913;
    private const Path                            = 801732;
    private const PathEdge                        = 2428705;
    private const PathNode                        = 801733;
    private const PathNodeProperty                = 801734;
    private const PathProperty                    = 801735;
    private const Phase                           = 1348558;
    private const PhaseShiftZoneSounds            = 1267336;
    private const PhaseXPhaseGroup                = 987581;
    private const PlayerCondition                 = 1045411;
    private const Positioner                      = 1251523;
    private const PositionerState                 = 1251506;
    private const PositionerStateEntry            = 1251533;
    private const PowerDisplay                    = 1332557;
    private const PowerType                       = 1266022;
    private const PrestigeLevelInfo               = 1275869;
    private const PvpBrawl                        = 1585723;
    private const PvpScalingEffect                = 1591100;
    private const PvpScalingEffectType            = 1591098;
    private const PvpSeason                       = 2966426;
    private const PvpSeasonRewardLevels           = 2470695;
    private const PvpTalent                       = 1302853;
    private const PvpTalentCategory               = 1891534;
    private const PvpTalentSlotUnlock             = 1950197;
    private const PvpTier                         = 2066871;
    private const QuestFactionReward              = 1282622;
    private const QuestFeedbackEffect             = 1343388;
    private const QuestInfo                       = 1120960;
    private const QuestLine                       = 973430;
    private const QuestLineXQuest                 = 973441;
    private const QuestMoneyReward                = 1139047;
    private const QuestObjective                  = 1251960;
    private const QuestPOIBlob                    = 1251882;
    private const QuestPOIPoint                   = 1251883;
    private const QuestPackageItem                = 801743;
    private const QuestSort                       = 1134585;
    private const QuestV2                         = 1139443;
    private const QuestV2CliTask                  = 1028735;
    private const QuestXGroupActivity             = 1573634;
    private const QuestXP                         = 1139378;
    private const QuestXUIQuestDetailsTheme       = 3448517;
    private const QuestXUiWidgetSet               = 3923421;
    private const RTPC                            = 3405439;
    private const RTPCData                        = 3405440;
    private const RafActivity                     = 3081207;
    private const RandPropPoints                  = 1310245;
    private const RecipeProgressionGroupEntry     = 3671785;
    private const RelicSlotTierRequirement        = 1716803;
    private const RelicTalent                     = 1671256;
    private const RenownRewards                   = 3743117;
    private const ResearchBranch                  = 1133729;
    private const ResearchField                   = 1133711;
    private const ResearchProject                 = 1134090;
    private const ResearchSite                    = 1134091;
    private const Resistances                     = 1135072;
    private const RewardPack                      = 1307156;
    private const RewardPackXCurrencyType         = 1307153;
    private const RewardPackXItem                 = 1307155;
    private const RibbonQuality                   = 1398908;
    private const RopeEffect                      = 3256786;
    private const RuneforgeLegendaryAbility       = 3500241;
    private const SDReplacementModel              = 1712172;
    private const SSAOSettings                    = 2056369;
    private const Scenario                        = 1139062;
    private const ScenarioEventEntry              = 1141065;
    private const ScenarioStep                    = 1132761;
    private const SceneScript                     = 801754;
    private const SceneScriptGlobalText           = 1758036;
    private const SceneScriptPackage              = 801755;
    private const SceneScriptPackageMember        = 801756;
    private const SceneScriptText                 = 1758037;
    private const ScheduledInterval               = 1327082;
    private const ScreenEffect                    = 1302849;
    private const ScreenEffectType                = 3063174;
    private const ScreenLocation                  = 1279416;
    private const SeamlessSite                    = 1328719;
    private const ServerMessages                  = 1301141;
    private const ShadowyEffect                   = 1239844;
    private const SiegeableProperties             = 1954391;
    private const SkillLine                       = 1240935;
    private const SkillLineAbility                = 1266278;
    private const SkillRaceClassInfo              = 1240406;
    private const SkySceneXPlayerCondition        = 3581893;
    private const Soulbind                        = 3488583;
    private const SoulbindConduit                 = 3594380;
    private const SoulbindConduitEnhancedSocket   = 4069554;
    private const SoulbindConduitItem             = 3604984;
    private const SoulbindConduitRank             = 3620681;
    private const SoulbindConduitRankProperties   = 3858895;
    private const SoulbindUIDisplayInfo           = 3490472;
    private const SoundAmbience                   = 1310628;
    private const SoundAmbienceFlavor             = 1267065;
    private const SoundBus                        = 1310246;
    private const SoundBusOverride                = 1598732;
    private const SoundEmitterPillPoints          = 1092317;
    private const SoundEmitters                   = 1092316;
    private const SoundEnvelope                   = 1693131;
    private const SoundFilter                     = 1271601;
    private const SoundFilterElem                 = 1267066;
    private const SoundKit                        = 1237434;
    private const SoundKitAdvanced                = 1237436;
    private const SoundKitChild                   = 1307289;
    private const SoundKitEntry                   = 1237435;
    private const SoundKitFallback                = 1307288;
    private const SoundOverride                   = 1266542;
    private const SoundParameter                  = 3405441;
    private const SoundProviderPreferences        = 1279417;
    private const SourceInfo                      = 1313612;
    private const SpamMessages                    = 1117088;
    private const SpecSetMember                   = 2057624;
    private const SpecializationSpells            = 1240335;
    private const SpecializationSpellsDisplay     = 2067238;
    private const Spell                           = 1140089;
    private const SpellActionBarPref              = 1019373;
    private const SpellActivationOverlay          = 1261603;
    private const SpellAuraOptions                = 1139952;
    private const SpellAuraRestrictions           = 981566;
    private const SpellAuraVisXChrSpec            = 1280615;
    private const SpellAuraVisibility             = 1280616;
    private const SpellCastTimes                  = 1134089;
    private const SpellCastingRequirements        = 1002166;
    private const SpellCategories                 = 1139939;
    private const SpellCategory                   = 1280619;
    private const SpellChainEffects               = 1343310;
    private const SpellClassOptions               = 979663;
    private const SpellClutterAreaEffectCounts    = 2428696;
    private const SpellClutterFrameRates          = 2428707;
    private const SpellClutterImpactModelCounts   = 2428708;
    private const SpellClutterKitDistances        = 2428697;
    private const SpellClutterMissileDist         = 2428733;
    private const SpellClutterWeaponTrailDist     = 2428698;
    private const SpellCooldowns                  = 1139924;
    private const SpellDescriptionVariables       = 1140004;
    private const SpellDispelType                 = 1137829;
    private const SpellDuration                   = 1137828;
    private const SpellEffect                     = 1140088;
    private const SpellEffectAutoDescription      = 1888495;
    private const SpellEffectEmission             = 1310248;
    private const SpellEquippedItems              = 1140011;
    private const SpellFlyout                     = 1146819;
    private const SpellFlyoutItem                 = 1134085;
    private const SpellFocusObject                = 1280620;
    private const SpellInterrupts                 = 1139906;
    private const SpellItemEnchantment            = 1362771;
    private const SpellItemEnchantmentCondition   = 1121834;
    private const SpellKeyboundOverride           = 1127327;
    private const SpellLabel                      = 1347275;
    private const SpellLearnSpell                 = 1001907;
    private const SpellLevels                     = 1140079;
    private const SpellMechanic                   = 1014438;
    private const SpellMisc                       = 1003144;
    private const SpellMissile                    = 897956;
    private const SpellMissileMotion              = 897955;
    private const SpellName                       = 1990283;
    private const SpellOverrideName               = 2618823;
    private const SpellPower                      = 982806;
    private const SpellPowerDifficulty            = 982804;
    private const SpellProceduralEffect           = 1140477;
    private const SpellProcsPerMinute             = 1133526;
    private const SpellProcsPerMinuteMod          = 1133525;
    private const SpellRadius                     = 1134584;
    private const SpellRange                      = 1146820;
    private const SpellReagents                   = 841946;
    private const SpellReagentsCurrency           = 1135239;
    private const SpellScaling                    = 1139940;
    private const SpellScript                     = 3055899;
    private const SpellScriptText                 = 3055901;
    private const SpellShapeshift                 = 1139929;
    private const SpellShapeshiftForm             = 1280618;
    private const SpellSpecialUnitEffect          = 1268903;
    private const SpellTargetRestrictions         = 1139993;
    private const SpellTotems                     = 1002162;
    private const SpellVisual                     = 897952;
    private const SpellVisualAnim                 = 1140479;
    private const SpellVisualColorEffect          = 1094006;
    private const SpellVisualEffectName           = 897948;
    private const SpellVisualEvent                = 1685317;
    private const SpellVisualKit                  = 897949;
    private const SpellVisualKitAreaModel         = 897951;
    private const SpellVisualKitEffect            = 1140480;
    private const SpellVisualKitModelAttach       = 897953;
    private const SpellVisualKitPicker            = 3989478;
    private const SpellVisualKitPickerEntry       = 3989479;
    private const SpellVisualMissile              = 897954;
    private const SpellVisualScreenEffect         = 3607312;
    private const SpellXDescriptionVariables      = 1724949;
    private const SpellXSpellVisual               = 1101657;
    private const StartupFiles                    = 1604265;
    private const Startup_Strings                 = 1375805;
    private const Stationery                      = 1140758;
    private const SummonProperties                = 1345276;
    private const TactKey                         = 1302850;
    private const TactKeyLookup                   = 1302851;
    private const Talent                          = 1369062;
    private const TaxiNodes                       = 1068100;
    private const TaxiPath                        = 1067802;
    private const TaxiPathNode                    = 1000437;
    private const TerrainColorGradingRamp         = 3501705;
    private const TerrainMaterial                 = 1307290;
    private const TerrainType                     = 1310249;
    private const TerrainTypeSounds               = 1284822;
    private const TextureBlendSet                 = 1328721;
    private const TextureFileData                 = 982459;
    private const TierTransition                  = 3076928;
    private const TotemCategory                   = 1134586;
    private const Toy                             = 988200;
    private const TradeSkillCategory              = 1301101;
    private const TradeSkillItem                  = 1329070;
    private const TransformMatrix                 = 1338702;
    private const TransmogDefaultLevel            = 2399695;
    private const TransmogHoliday                 = 1589454;
    private const TransmogIllusion                = 3580450;
    private const TransmogSet                     = 1376213;
    private const TransmogSetGroup                = 1576116;
    private const TransmogSetItem                 = 1376212;
    private const TransportAnimation              = 1140686;
    private const TransportPhysics                = 1121973;
    private const TransportRotation               = 1140687;
    private const Trophy                          = 975024;
    private const UIChromieTimeExpansionInfo      = 3488582;
    private const UICovenantAbility               = 3502042;
    private const UICovenantPreview               = 3502043;
    private const UIDungeonScoreRarity            = 4065278;
    private const UIEventToast                    = 3946498;
    private const UIExpansionDisplayInfo          = 1729547;
    private const UIExpansionDisplayInfoIcon      = 1729546;
    private const UIScriptedAnimationEffect       = 3556601;
    private const UISplashScreen                  = 2960122;
    private const UiCamFbackTransmogChrRace       = 1261406;
    private const UiCamFbackTransmogWeapon        = 1261407;
    private const UiCamera                        = 1120287;
    private const UiCameraType                    = 1120288;
    private const UiCanvas                        = 1989363;
    private const UiCovenantDisplayInfo           = 3509132;
    private const UiItemInteraction               = 3182424;
    private const UiMap                           = 1957206;
    private const UiMapArt                        = 1957202;
    private const UiMapArtStyleLayer              = 1957208;
    private const UiMapArtTile                    = 1957210;
    private const UiMapAssignment                 = 1957219;
    private const UiMapFogOfWar                   = 2006972;
    private const UiMapFogOfWarVisualization      = 2006973;
    private const UiMapGroupMember                = 1957204;
    private const UiMapLink                       = 2030690;
    private const UiMapXMapArt                    = 1957217;
    private const UiModelScene                    = 1548215;
    private const UiModelSceneActor               = 1548214;
    private const UiModelSceneActorDisplay        = 1548216;
    private const UiModelSceneCamera              = 1548213;
    private const UiPartyPose                     = 1993323;
    private const UiQuestDetailsTheme             = 3448518;
    private const UiTextureAtlas                  = 897470;
    private const UiTextureAtlasElement           = 1989276;
    private const UiTextureAtlasMember            = 897532;
    private const UiTextureKit                    = 939159;
    private const UiWidget                        = 1983278;
    private const UiWidgetConstantSource          = 1983639;
    private const UiWidgetDataSource              = 1983640;
    private const UiWidgetMap                     = 2322531;
    private const UiWidgetSet                     = 3055925;
    private const UiWidgetStringSource            = 1983641;
    private const UiWidgetVisTypeDataReq          = 2740907;
    private const UiWidgetVisualization           = 1983276;
    private const UiWidgetXWidgetSet              = 3386363;
    private const UnitBlood                       = 1284821;
    private const UnitBloodLevels                 = 1268904;
    private const UnitCondition                   = 1120959;
    private const UnitPowerBar                    = 1237753;
    private const Vehicle                         = 1368621;
    private const VehiclePOIType                  = 3311405;
    private const VehicleSeat                     = 1345447;
    private const VehicleUIIndSeat                = 1279741;
    private const VehicleUIIndicator              = 1279740;
    private const Vignette                        = 892861;
    private const VirtualAttachment               = 1634482;
    private const VirtualAttachmentCustomization  = 1634480;
    private const VocalUISounds                   = 1267067;
    private const VolumeFogCondition              = 3587230;
    private const WMOAreaTable                    = 1355528;
    private const WMOMinimapTexture               = 1323241;
    private const WaterfallData                   = 2565222;
    private const WaypointEdge                    = 2565258;
    private const WaypointNode                    = 2565265;
    private const WaypointSafeLocs                = 2820850;
    private const WbAccessControlList             = 879634;
    private const WbCertWhitelist                 = 879591;
    private const WeaponImpactSounds              = 1267648;
    private const WeaponSwingSounds2              = 1267068;
    private const WeaponTrail                     = 982461;
    private const WeaponTrailModelDef             = 1239843;
    private const WeaponTrailParam                = 1239842;
    private const Weather                         = 1343311;
    private const WeatherXParticulate             = 1965591;
    private const WeeklyRewardChestThreshold      = 3580962;
    private const WindSettings                    = 943871;
    private const WorldBossLockout                = 975279;
    private const WorldChunkSounds                = 1267069;
    private const WorldEffect                     = 1343312;
    private const WorldElapsedTimer               = 1135240;
    private const WorldMapOverlay                 = 1134579;
    private const WorldMapOverlayTile             = 1957212;
    private const WorldStateExpression            = 1332558;
    private const WorldStateZoneSounds            = 1266941;
    private const World_PVP_Area                  = 1310255;
    private const ZoneIntroMusicTable             = 1310251;
    private const ZoneLight                       = 1310253;
    private const ZoneLightPoint                  = 1310256;
    private const ZoneMusic                       = 1310254;
    private const ZoneStory                       = 1797864;
}
